version: '3.1'
services:
  redis:
    image: redis:latest
    container_name: rd01
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    links:
      - redis
    depends_on:
      - redis
  celery:
    build: .
    container_name: cl01
    command: celery -A server_polling_app worker -l info
    links:
      - redis
    depends_on:
      - redis
